"""Coverage audit: every Phase 1 inventory item must appear in the built site.
Usage: python3 site/tools/audit.py   (exit 1 if anything is missing)
"""
import sys, html, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
text = html.unescape((ROOT / "dist" / "index.html").read_text()).lower()
text = re.sub(r"\s+", " ", text)

INVENTORY = {
    "1 Intro & epidemiology": ["filters blood", "metabolic wastes", "electrolyte", "acid-base", "fluid volume and blood pressure", "kidney failure", "nephrolithiasis", "renal calculi", "50% of all women", "noncancerous enlargement", "5–10%", "more than half of adults", "6.5%"],
    "2 Anatomy": ["ureters", "urinary bladder", "shorter in females", "cortex", "medulla", "renal pelvis", "minor calyx", "major calyx", "renal capsule", "renal pyramid", "renal column", "renal papilla", "renal hilum", "renal sinus", "renal lobe", "renal artery", "renal vein", "structural and functional unit", "glomerulus", "bowman", "proximal convoluted tubule", "loop of henle", "distal convoluted tubule", "collecting duct", "papillary duct", "afferent arteriole", "efferent arteriole", "macula densa", "vasa recta", "descending limb", "ascending limb", "corticomedullary", "share the urethra", "semen and other secretions", "prostate gland surrounds the urethra", "seminal vesicles", "spermatozoa", "epididymis", "vas deferens", "ejaculatory duct", "bulbourethral", "cowper", "pubic bone", "glans penis", "bulb of penis", "scrotum"],
    "3 Assessment": ["standard precautions", "mimic other abdominal problems", "bacterial infection", "extension of the ureter by a kidney stone", "prostate enlargement", "extremes of activity", "how the patient will be moved", "sample", "last oral intake", "visceral", "referred", "opqrst", "provocation", "four quadrants", "nine anatomic segments", "hypochondriac", "epigastric", "periumbilical", "hypogastric", "lumbar", "iliac", "every 5 minutes", "flank tenderness", "inspect the genitalia", "ecg monitoring", "rapid deterioration", "serial vital signs", "position of comfort", "antiemetic", "do not withhold pain control", "liver", "gallbladder", "cecum", "appendix", "costal arch", "spleen", "stomach", "umbilicus", "small intestine", "colon", "inguinal ligament", "rectum", "pubic symphysis", "iliac crest"],
    "4 UTI": ["antibiotics", "lower urinary tract", "more common in women", "spread if untreated", "painful urination", "frequent urges", "difficulty urinating", "restless and uncomfortable", "pyelonephritis or sepsis", "nearest appropriate medical facility"],
    "5 Catheters": ["foley catheter", "latex or plastic tube", "continuous outflow", "measure urine output", "urine backflow", "do not lift the drainage bag", "pull out or kink", "balloon is deflated"],
    "6 Retention & incontinence": ["incomplete emptying", "urethral obstruction", "nerve damage", "loss of bladder control", "urge incontinence", "within seconds or minutes", "overflow incontinence", "constant, continual slow flow"],
    "7 Kidney stones": ["insoluble salts or uric acid", "diet", "hydration", "family history", "hypertension", "calcium stones", "hereditary component", "struvite", "uric acid stones", "cystine", "almost always experience pain", "guard", "palpation may be difficult", "hematuria", "hydronephrosis", "hydroureter", "stricture", "analgesia if local protocols allow", "tamsulosin", "flomax", "alpha (α)-blocker", "pass on their own", "extracorporeal shock wave lithotripsy", "cystoscopy with stent", "percutaneous nephrostomy", "youtu.be/z-w1qo8ztci"],
    "8 AKI": ["sudden decrease in filtration", "toxins to accumulate", "up to 50%", "20%", "70%", "500 ml/day", "0.5 ml/kg/h", "anuria", "complete cessation", "generalized edema", "acid buildup", "nitrogenous", "volume overload", "hyperkalemia", "uremia", "metabolic acidosis", "prerenal", "intrarenal", "postrenal", "impaired mentation", "fluid retention", "tachycardia", "pr and qt", "hypoperfusion", "hepatorenal syndrome", "portal hypertension", "glomeruli", "tubul", "interstiti", "blockage of urine flow", "table 21-2", "dizziness", "thirst", "joint pain", "headache", "seizure", "distended bladder", "peripheral edema", "pale, cool, moist skin", "darkening of urine", "heart failure", "ascites", "signs of infection", "iv bolus", "comorbid"],
    "9 CKD": ["permanent loss of nephrons", "scarring", "azotemia", "systemic complications", "altered level of consciousness", "lethargy", "nausea", "pericarditis and pulmonary edema", "not performed in the field", "calm manner"],
    "10 ESRD": ["untreated acute or chronic", "lost all ability", "dialysis or renal transplant", "weakness", "dehydration", "missed dialysis", "shortness of breath", "uremic frost", "muscle twitching", "coagulopathy", "chest pain", "confusion", "seizures", "coma"],
    "11 Renal failure & K+": ["12-lead ecg to check electrolytes", "etco", "hemodialysis capabilities", "fluids as necessary", "dysrhythmias", "peaked t", "wide qrs", "stabilizes the cardiac cell membranes", "does not lower k", "digoxin toxicity", "insulin + glucose", "beta agonists", "sodium bicarbonate", "pre-syncope", "hr 52", "93/68", "95%", "36.5", "prolonged cap"],
    "12 Dialysis": ["toxic wastes", "removing excess fluid", "restoring the normal balance", "peritoneal dialysis", "capd", "apd", "hemodialysis", "fistula", "av shunt", "looped graft", "community dialysis facility", "at home", "2 or 3", "3 to 5", "human error", "cannulation", "connection or disconnection", "muscle cramps", "infections at the fistula", "hypotension and shock", "potassium imbalance", "disequilibrium syndrome", "air embolism", "accidental disconnection", "malfunction of the machine", "rapid shifts in fluids", "cerebral edema", "serum osmolality", "disorientation", "dizziness", "table 21-3", "50 ml of normal saline", "clamp it off", "atropine", "sending facility", "supportive treatment", "left lateral recumbent", "10°", "turn off", "sitting position", "diuretic", "caution in administering", "pericardial tamponade", "uremic pericarditis"],
    "13 Male GU": ["posterior border of the testis", "orchitis", "prehospital management is supportive", "fournier gangrene", "subcutaneous tissue and muscle", "erythematous", "gray-black", "aggressive iv fluids", "prompt transport", "priapism", "persistent erection", "privacy", "assumptions about the cause", "respect", "spinal cord injury", "analgesics", "phimosis", "cold compress", "paraphimosis", "true emergency", "necrosis of the glans", "nonmalignant enlargement", "difficulty starting urine flow", "increased urination at night", "urinary retention", "testicular mass", "benign cystic masses", "varicocele", "painless solid lump", "testicular torsion", "spermatic cord", "reduces blood flow", "usually unilateral", "carefully and promptly"],
}

missing = {k: [t for t in v if t.lower() not in text] for k, v in INVENTORY.items()}
total = sum(len(v) for v in INVENTORY.values())
miss_n = sum(len(v) for v in missing.values())
print(f"Coverage audit: {total - miss_n}/{total} inventory items found")
for k, v in missing.items():
    if v:
        print(f"  MISSING in {k}: {v}")
sys.exit(1 if miss_n else 0)
